### ISSUE TITLE
able to eat food and wake up in the morning?

### ISSUE THREAD

**Issue by emeryplyler** [Auroali/sanguinis-luxuria#1]
Somehow I'm able to eat human food and have it refill my blood bar, though I haven't leveled up at all so this may be intentional.
I've also had a lot of trouble with sleeping during the day. It seems to add time to whenever I slept instead of letting me wake up at nightfall.
(Other than that I really love this mod and prefer it to other vampire mods.)

**Comment by Auroali** [comment]
food filling your blood bar isn’t intentional, do you have any other mods installed?

sleeping adding time instead if skipping to night is also not intended and something i’ve also noticed when playing with other mods, i just haven’t figured out exactly what causes it yet. i’ll look into properly fixing it when i get home

**Comment by emeryplyler** [comment]
Sleeping seems to work perfectly when playing without any other mods, but I was still able to eat food. I'm playing with Fabric 0.15.7.

**Comment by Auroali** [comment]
could you try [v1.0.3](https://github.com/Auroali/sanguinis-luxuria/releases/tag/v1.0.3) and see if it works? you should be able to eat food, but it shouldn't fill your blood bar. it should also properly skip to night now

**Comment by Auroali** [comment]
should be fixed in [3c1b68e](https://github.com/Auroali/sanguinis-luxuria/commit/3c1b68e898455d09aec874388f7f0589dec40fdb), i'll backport it to 1.19 and try to get the update out soon. sorry for taking so long
